[project]
name = "backend"
version = "0.1.0"
description = "An agent aimed to analyze datasets by calling python and SQL tooling"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.4",
]
